// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNi3dNmrnBU1_Y2p34Sgip9A8Isa4EQA',
    appId: '1:389439390322:web:9b8856bd4cb31e3a6878eb',
    messagingSenderId: '389439390322',
    projectId: 'act13-17590',
    authDomain: 'act13-17590.firebaseapp.com',
    storageBucket: 'act13-17590.firebasestorage.app',
    measurementId: 'G-DWFK1H5F1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTSPcQVNcoqSHOAjxF7ps8ewMjx2k5q8',
    appId: '1:389439390322:android:c89dc77472f4a7766878eb',
    messagingSenderId: '389439390322',
    projectId: 'act13-17590',
    storageBucket: 'act13-17590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcMl9v1qdZ2jaCoSsCqZTp_7aGGpTrPPM',
    appId: '1:389439390322:ios:a0257d6aee442de16878eb',
    messagingSenderId: '389439390322',
    projectId: 'act13-17590',
    storageBucket: 'act13-17590.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcMl9v1qdZ2jaCoSsCqZTp_7aGGpTrPPM',
    appId: '1:389439390322:ios:a0257d6aee442de16878eb',
    messagingSenderId: '389439390322',
    projectId: 'act13-17590',
    storageBucket: 'act13-17590.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgNi3dNmrnBU1_Y2p34Sgip9A8Isa4EQA',
    appId: '1:389439390322:web:3620522cfc4dfc6b6878eb',
    messagingSenderId: '389439390322',
    projectId: 'act13-17590',
    authDomain: 'act13-17590.firebaseapp.com',
    storageBucket: 'act13-17590.firebasestorage.app',
    measurementId: 'G-XTSNWHQ2CX',
  );
}
